Main svc
Nikitacauselove/java-explore-with-me pull request #4
Opened 2023-11-06 13:10 UTC by Nikitacauselove

2023-11-14 10:51 UTC, LexLippi requested changes
Привет!

Хорошая работа!

Есть пара замечаний и советов, которые необходимо исправить!

Желаю удачи!

2023-11-14 10:51 UTC, LexLippi commented on ewm/src/main/java/ru/practicum/ewm/service/EventService.java
> +            for (Request request : requests) {
А почему разные типы `forEach` используешь?
Здесь стандартный, а ниже для `Stream API`, лучше везде единого стиля придерживаться

Лично мне больше, через `Stream API` нравится

2023-11-17 14:00 UTC, Nikitacauselove commented on stats/server/src/main/java/ru/practicum/server/endpointhit/EndpointHitRepository.java
> +            "where hit.timestamp between :start and :end and (coalesce(:uris, null) is null or hit.uri in :uris) " +
Я попробовал использовать `:uris is null`, но в таком случае возникает ошибка

2023-11-17 14:01 UTC, Nikitacauselove commented on stats/dto/src/main/java/ru/practicum/dto/ViewStatisticsDto.java
> +@Setter
Я добавил аннотацию `@Data`, где это было возможно. В некоторых местах возникает ошибка десериализации, поэтому там она не используется

2023-11-17 18:11 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи с заключительным этапом дипломного проекта!

2023-11-17 23:17 UTC, merged